"""
Usage:
    hpr.py [-h]
    hpr.py [-r PATH] init help
    hpr.py [-r PATH] init <template> [-n]
    hpr.py [-r PATH] sample [help|create|deploy]
    hpr.py [-r PATH] bases [help|generate|pack]

Options:
-h --help             Show this
-r PATH --root=PATH   Specify the root path of the project, where the
                      configuration file must be located [default: .]
-n --no-quiet-params  Do not include no-output template case files used for
                      time measurements.

Commands:
    init              Create configuration file, directories, and copy template files.
        help          Print detailed information of this command
    sample            Sampling stage actions
        help          Print detailed information of this command
        create        Create directory structure
        deploy        Deploy template cases in directories
    bases             Basis creation stage actions
        help          Print detailed information of this command
        generate      Generate bases
        pack          Create dataset files
"""

from pathlib import Path
from docopt import docopt
from common import Common
import sampling


def _process_arguments(args):
    """
    Process arguments

    Parameters:
        args: arguments dictionary generated by docopts

    Return:
        string with keyword
    """

    # Debug:
    #from pprint import pprint
    #pprint(args)

    keyword = ""

    if args["init"]:
        if args["help"]:
            keyword = "INIT_HELP"
        else:
            keyword = "INIT"

    if args["sample"]:
        if args["help"]:
            keyword = "SAMPLE_HELP"
        elif args["create"]:
            keyword = "SAMPLE_CREATE"
        elif args["deploy"]:
            keyword = "SAMPLE_DEPLOY"
        else:
            keyword = "SAMPLE"

    if args["bases"]:
        if args["help"]:
            keyword = "BASES_HELP"
        elif args["generate"]:
            keyword = "BASES_GENERATE"
        elif args["pack"]:
            keyword = "BASES_PACK"
        else:
            keyword = "BASES"

    return keyword


def init_func(template_path, params_quiet_flag):
    """Writes and creates initial files and directory structure at root path.
Root path can be passed when invoking the command, if missing the current
directory (".") is assumed.

- Checks if configurarion file is present
- If missing, writes a file with default values
- Checks template case files exists (including no-output parameters file if params_quiet
  option is set)
- Creates sampling directory (location passed as argument)
- Copies template files to sampling directory
"""

    # Write initial configuration file
    conf_file = C.root_path / "configuration.json"
    if conf_file.is_file():
        print("File {} exists. Skipping.".format(conf_file))
    else:
        C.dump_config(conf_file)
        print(
            "Written configuration file {}.".format(conf_file)
        )

    # Check that Kratos case files exist
    paths = [
        template_path / "MainKratos.py",
        template_path / "model.mdpa",
        template_path / "materials.json",
        template_path / "ProjectParameters.json",
        template_path / C.context["training_strain_fname"],
    ]
    if params_quiet_flag:
        paths.append(template_path / "ProjectParameters_quiet.json",)

    for p in paths:
        if not p.exists():
            print("Missing template file {}. Aborting.".format(p))
            exit()

    # Create sampling dir and copy Kratos case files from template directory
    if not C.training_path.exists():
        C.training_path.mkdir()
        print("Created sampling directory {}".format(C.training_path))
    else:
        print("Directory {} exists. Skipping.".format(C.training_path))

    # Copy template files to sampling directory
    for src in paths:
        dest = C.training_path / src.name
        dest.write_text(src.read_text())
    print("Template files copied to sampling directory")

    return


def sample_create():
    """Creates file structure for sampling.
Requires a file with strain tensors (voigt notation) for each trajectory."""
    strain_set = C.parse_training_strain_set()

    for i, line in enumerate(strain_set):
        case_path = C.training_path / C.case_name(i)
        strain_vector = [float(x) for x in line.split()]
        sampling.create_case_dir(case_path, strain_vector)
        sampling.create_launch_script(case_path)
        print(case_path.name, strain_vector)


#####################################################################
# Main
#####################################################################

if __name__ == "__main__":

    ARGS = docopt(__doc__, version="v0.9")
    KEYWORD = _process_arguments(ARGS)

    C = Common(root_path=Path(ARGS["--root"]))

    if KEYWORD == "INIT_HELP":
        print(init_func.__doc__)
    elif KEYWORD == "INIT":
        init_func(Path(ARGS["<template>"]), not ARGS["--no-quiet-params"])
    elif KEYWORD == "SAMPLE_HELP":
        print(sample_create.__doc__)
    elif KEYWORD == "SAMPLE_CREATE":
        sample_create()
    elif KEYWORD == "SAMPLE_DEPLOY":
        sample_create()
    elif KEYWORD == "SAMPLE":
        print(3)
    elif KEYWORD == "BASES_HELP":
        print(3)
    elif KEYWORD == "BASES_GENERATE":
        print(3)
    elif KEYWORD == "BASES_PACK":
        print(3)
    elif KEYWORD == "BASES":
        print(3)
    else:
        print("Need a command. Try with --help.")
        exit()
