#!/usr/bin/env python3
"""
hprfe2 v0.9
Marcelo Raschi <marcelo.raschi@gmail.com>
Utilities for HPRFE2 modal bases datasets

Usage:
    hprfe2 (--help | --version)
    hprfe2 [-v | -vv] [-r PATH] <command> [<args>...]

Options:
    -h --help             Print this help message and exit
    -V --version          Print version information and exit
    -v                    Verbose output (-v verbose, -vv debug)
    -r PATH --root=PATH   Specify the root path of the project, where the
                          configuration file must be located [default: .]

Commands:
    init        Create configuration file, directories, and copy template files
    deploy      Deploy template cases for sampling
    generate    Generate bases and IP sets
    pack        Create dataset files
    resources   Create datasets for fields reconstruction
    validate    Generate 1ip-multiscale validation cases

See 'hprfe2 <command> help' for more information on a specific command.
"""
# TODO
# update python to 3.8 in acuario
# get rid of Kratos banner!
# change file modes 0644
# change launchers file mode 755 and add env
# change dirs modes (755?)
# imporve commands' help
# update hardcoded filename here
# dump config with only basic options
# fix logger
# fix logger messages (make them consistent)
# show relative paths

import logging
from pathlib import Path
from docopt import docopt
import common
import sampling
import bases
import roc
import pack
#import reconstruction
import multiscale

## add verbosity level
#logging.VERBOSE = 15  # between DEBUG and INFO
#logging.__all__ += ['VERBOSE']
#logging.addLevelName(logging.VERBOSE, 'VERBOSE')
#logger = logging.getLogger("hprfe2")
#setattr(logger, 'verbose', lambda message,
#        *args: logger._log(logging.VERBOSE, message, args))
#
#
#class CustomFormatter(logging.Formatter):
#    """Logging Formatter to add colors and count warning / errors"""
#
#    green = "\x1b[32;21m"
#    custom = "\x1b[39;21m"
#    grey = "\x1b[38;21m"
#    yellow = "\x1b[33;21m"
#    red = "\x1b[31;21m"
#    bold_red = "\x1b[31;1m"
#    reset = "\x1b[0m"
#    #format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s (%(filename)s:%(lineno)d)"
#    format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s (%(filename)s:%(lineno)d)"
#
#    FORMATS = {
#        logging.DEBUG: green + format + reset,
#        logging.VERBOSE: custom + format + reset,  # VERBOSE
#        logging.INFO: grey + format + reset,
#        logging.WARNING: yellow + format + reset,
#        logging.ERROR: red + format + reset,
#        logging.CRITICAL: bold_red + format + reset
#    }
#
#    def format(self, record):
#        log_fmt = self.FORMATS.get(record.levelno)
#        formatter = logging.Formatter(log_fmt)
#        return formatter.format(record)


def validate():
    """Run several checks before running."""

    # Check that root path is correct (wrt config file)
    if not C.config_file.is_file():
        logger.error("{} not found. Correct root_path value?".format(C.config_file))
        exit()

    return


def init(template_path, params_quiet_flag):
    """\
Writes and creates initial files and directory structure at root path.
Root path can be passed when invoking the command, if missing the current
directory (".") is assumed.

    - Checks if configurarion file is present
    - If missing, writes a file with default values
    - Checks template case files exists (including no-output parameters file
      if params_quiet option is set)
    - Creates sampling directory (location passed as argument)
    - Copies template files to sampling directory
"""

    # Create basic dir structure
    for p in [C.training_path, C.bases_path, C.datasets_path]:
        if not p.exists():
            p.mkdir()
            logger.info("Created directory {}".format(p))
        else:
            logger.info("Directory {} exists. Skipping.".format(p))

    # Write initial configuration file
    if C.config_file.is_file():
        logger.info("File {} exists. Skipping.".format(C.config_file))
    else:
        C.dump_config(C.config_file)
        logger.info("Written configuration file {}.".format(C.config_file))

    # Check that Kratos case files exist
    paths = [
        template_path / "MainKratos.py",
        template_path / "model.mdpa",
        template_path / "materials.json",
        template_path / "ProjectParameters.json",
        template_path / C.config["training_strain_fname"],
    ]
    if params_quiet_flag:
        paths.append(
            template_path / "ProjectParameters_quiet.json",
        )

    for p in paths:
        if not p.exists():
            logger.error("Missing template file {}. Aborting.".format(p))
            exit()

    # Copy template files to sampling directory
    for src in paths:
        dest = C.training_path / src.name
        dest.write_text(src.read_text())
    logger.info("Template files copied to sampling directory")

    return


def deploy():
    """\
Creates file structure for sampling and directory structure for training.
Requires a file with strain tensors (voigt notation) for each trajectory.
sample create: creates directory structure
sample deploy: populates directories"""

    strain_set = C.parse_training_strain_set()

    for i, line in enumerate(strain_set):
        case_path = C.training_path / C.case_name(i)
        strain_vector = [float(x) for x in line.split()]
        sampling.create_case_dir(case_path, strain_vector)
        sampling.create_run_script(case_path)
        logger.info("{} {}".format(case_path.name, strain_vector))
    sampling.create_launchers(C.training_path)


def generate():
    """Creates file structure from the computation of bases"""

    # Generate bases
    bases.run(C)

    # Compute ROC ip sets
    roc.write_ip_sets(C)
    return

def resources():
    """ doc """

    # workaround: move import here, to avoid printing Kratos banner
    import reconstruction

    # Computes data for displacement reconstruction
    reconstruction.reconstruct_displacement_all(C)

    # Computes data for damage reconstruction
    reconstruction.reconstruct_damage_all(C)
    return


#####################################################################
# Main
#####################################################################

if __name__ == "__main__":

    ARGS = docopt(__doc__, version="v0.9", options_first=True)
    # Debug:
    #from pprint import pprint
    #print("Global arguments:")
    #pprint(ARGS)

    # Configure logger
    LOGLEVEL = [logging.INFO, logging.INFO, logging.DEBUG][ARGS['-v']]
    #LOGLEVEL = [logging.INFO, logging.VERBOSE, logging.DEBUG][ARGS['-v']]
    logging.basicConfig(
        format="[%(asctime)s] %(message)s",
        datefmt="%H:%M:%S",
        level=LOGLEVEL,
    )
    logger = logging.getLogger(__name__)
    #print(logging.__all__)
    #print(logging.DEBUG)
    #print(logging.VERBOSE)
    #print(logging.INFO)
    #print(logging.WARNING)
    #print(logging.ERROR)
    #print(logging.CRITICAL)

    # create console handler with a higher log level
    #ch = logging.StreamHandler()
    #ch.setLevel(LOGLEVEL)
    #ch.setFormatter(CustomFormatter())
    
    #logger.setLevel(30)
    #logger.addHandler(ch)

    #fh = logging.FileHandler("{}".format(C.root_path / "hprfe2.log"))
    #fh.setLevel(logging.DEBUG)
    #fh.setFormatter(logging.Formatter("[%(asctime)s] xxx %(message)s"))
    # ch = logging.StreamHandler()
    # ch.setLevel(logging.DEBUG)
    # ch.setFormatter(logging.Formatter("[%(asctime)s] %(message)s"))
    #logger = logging.getLogger(__name__)
    #logger.addHandler(fh)
    # logger.addHandler(ch)

    # Debug logger:
    #print("Testing logger")
    #logger.debug("DEBUG log level")
    ##logger.verbose("VERBOSE log level")
    #logger.info("INFO log level")
    #logger.warning("WARNING log level")
    #logger.error("ERROR log level")
    #logger.critical("CRITICAL log level")
    # end of logger configuration
 
    #logger.info("--- STARTED ---")
    
    ROOT = Path(ARGS["--root"])
    C = common.Common(ROOT)

    # Launch tree
    if ARGS['<command>'] == 'init':
        if "help" in ARGS['<args>']:
            exit(init.__doc__)
        init(Path(ARGS["<args>"][0]), True)
    elif ARGS['<command>'] == 'deploy':
        if "help" in ARGS['<args>']:
            exit(deploy.__doc__)
        validate()
        deploy()
    elif ARGS['<command>'] == 'generate':
        if "help" in ARGS['<args>']:
            exit(bases.__doc__ + roc.__doc__)
        validate()
        generate()
    elif ARGS['<command>'] == 'pack':
        if "help" in ARGS['<args>']:
            exit(bases.__doc__)
        validate()
        pack.write_datasets(C)
    elif ARGS['<command>'] == 'resources':
        if "help" in ARGS['<args>']:
            # workaround: avoiding importing module until use, banner Kratos
            #print(reconstruction.__doc__)
            #print(reconstruction.reconstruct_displacement.__doc__)
            #print(reconstruction.reconstruct_damage.__doc__)
            # Printting our own help for now...
            exit("Reconstruction help: add docs here")
        validate()
        resources()
    elif ARGS['<command>'] == 'validate':
        if "help" in ARGS['<args>']:
            exit(multiscale.__doc__)
        validate()
        multiscale.run(C)
    elif ARGS['<command>'] in ['help', None]:
        exit(__doc__)
    else:
        exit("{} is not a hprfe2 command. See '--help'.".format(ARGS['<command>']))

    #logger.info("--- FINISH ---")
        
