#!/usr/bin/env python3
"""
hprfe2
Marcelo Raschi <marcelo.raschi@gmail.com>
Utilities for HPRFE2 modal bases datasets

Usage:
    hprfe2 (--help | --version)
    hprfe2 [-v | -vv] [-r PATH] <command> [<args>...]

Options:
    -h --help             Print this help message and exit
    -V --version          Print version information and exit
    -v                    Verbose output (-v verbose, -vv debug)
    -r PATH --root=PATH   Specify the root path of the project, where the
                          configuration file must be located [default: .]

Commands:
    config      Create default configuration file
    sample      Create sampling datastructure and scripts from a given template case
    generate    Generate bases and IP sets
    resources   Create datasets for fields reconstruction
    validate    Generate 1ip-multiscale validation cases

See 'hprfe2 <command> help' for more information on a specific command.

"""
# TODO
# get rid of Kratos banner!
# imporve commands' help
# update hardcoded filename here
# fix logger
# fix logger messages (make them consistent)
# show relative paths

import sys
import logging
from pathlib import Path
from docopt import docopt
import common
import sampling
import bases
import roc
import pack

# import reconstruction
import multiscale

## add verbosity level
# logging.VERBOSE = 15  # between DEBUG and INFO
# logging.__all__ += ['VERBOSE']
# logging.addLevelName(logging.VERBOSE, 'VERBOSE')
# logger = logging.getLogger("hprfe2")
# setattr(logger, 'verbose', lambda message,
#        *args: logger._log(logging.VERBOSE, message, args))
#
#
# class CustomFormatter(logging.Formatter):
#    """Logging Formatter to add colors and count warning / errors"""
#
#    green = "\x1b[32;21m"
#    custom = "\x1b[39;21m"
#    grey = "\x1b[38;21m"
#    yellow = "\x1b[33;21m"
#    red = "\x1b[31;21m"
#    bold_red = "\x1b[31;1m"
#    reset = "\x1b[0m"
#    #format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s (%(filename)s:%(lineno)d)"
#    format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s (%(filename)s:%(lineno)d)"
#
#    FORMATS = {
#        logging.DEBUG: green + format + reset,
#        logging.VERBOSE: custom + format + reset,  # VERBOSE
#        logging.INFO: grey + format + reset,
#        logging.WARNING: yellow + format + reset,
#        logging.ERROR: red + format + reset,
#        logging.CRITICAL: bold_red + format + reset
#    }
#
#    def format(self, record):
#        log_fmt = self.FORMATS.get(record.levelno)
#        formatter = logging.Formatter(log_fmt)
#        return formatter.format(record)


def config(args):
    """\

Usage:
    hprfe2 config [--advanced|--full]

Arguments:
    -a --advanced  basic and advanced user options
    -f --full      basic, advanced and and system options

Writes an initial configuration file with default values at root path.
"""

    # Don't overwrite existing configuration file
    if C.config_file.is_file():
        logger.info("File {} exists. Skipping.".format(C.config_file))
        return

    # Write initial configuration file
    if not args["--advanced"] and not args["--full"]:
        C.dump_config(C.config_file, mode="defaults_basic")
        logger.info("Written configuration file {}.".format(C.config_file))
    elif args["--advanced"]:
        C.dump_config(C.config_file, mode="defaults_advanced")
        logger.info("Written advanced configuration file {}.".format(C.config_file))
    elif args["--full"]:
        C.dump_config(C.config_file, mode="defaults_full")
        logger.info("Written full configuration file {}.".format(C.config_file))

    return


def generate(common, args):
    """\

Usage:
    hprfe2 [-v] [-r PATH] generate [-f]

Arguments:
    -f --force                Overides existing files
    -v --verbose              Verbose output
    -r PATH --root=PATH       Specify the root path of the project, where the
                              configuration file must be located [default: .]

Computes modal bases of energy, strain and damage, from snapshot of the solutions
obtained in the sampling stage.
"""

    # Create directory if not present already
    for p in [common.bases_path, common.datasets_path]:
        if not p.exists():
            p.mkdir()
            logger.info("Created directory {}".format(p))

    if args["--force"]:
        common.config["reuse_existing_files"] = False

    # Generate bases
    bases.run(common)

    # Compute ROC ip sets
    roc.write_ip_sets(common)

    # Generate rvelaw datasets
    pack.write_datasets(common)
    return


def resources():
    """ doc """

    # workaround: move import here, to avoid printing Kratos banner
    import reconstruction

    # Computes data for displacement reconstruction
    reconstruction.reconstruct_displacement_all(C)

    # Computes data for damage reconstruction
    reconstruction.reconstruct_damage_all(C)
    return


#####################################################################
# Main
#####################################################################

if __name__ == "__main__":

    ARGS = docopt(__doc__, version="v1.0.beta", options_first=True)
    # Debug:
    # from pprint import pprint
    # print("Global arguments:")
    # pprint(ARGS)

    # Configure logger
    LOGLEVEL = [logging.INFO, logging.INFO, logging.DEBUG][ARGS["-v"]]
    # LOGLEVEL = [logging.INFO, logging.VERBOSE, logging.DEBUG][ARGS['-v']]
    logging.basicConfig(
        format="[%(asctime)s] %(message)s",
        datefmt="%H:%M:%S",
        level=LOGLEVEL,
    )
    logger = logging.getLogger(__name__)
    # print(logging.__all__)
    # print(logging.DEBUG)
    # print(logging.VERBOSE)
    # print(logging.INFO)
    # print(logging.WARNING)
    # print(logging.ERROR)
    # print(logging.CRITICAL)

    # create console handler with a higher log level
    # ch = logging.StreamHandler()
    # ch.setLevel(LOGLEVEL)
    # ch.setFormatter(CustomFormatter())

    # logger.setLevel(30)
    # logger.addHandler(ch)

    # fh = logging.FileHandler("{}".format(C.root_path / "hprfe2.log"))
    # fh.setLevel(logging.DEBUG)
    # fh.setFormatter(logging.Formatter("[%(asctime)s] xxx %(message)s"))
    # ch = logging.StreamHandler()
    # ch.setLevel(logging.DEBUG)
    # ch.setFormatter(logging.Formatter("[%(asctime)s] %(message)s"))
    # logger = logging.getLogger(__name__)
    # logger.addHandler(fh)
    # logger.addHandler(ch)

    # Debug logger:
    # print("Testing logger")
    # logger.debug("DEBUG log level")
    ##logger.verbose("VERBOSE log level")
    # logger.info("INFO log level")
    # logger.warning("WARNING log level")
    # logger.error("ERROR log level")
    # logger.critical("CRITICAL log level")
    # end of logger configuration

    # logger.info("--- STARTED ---")

    ROOT = Path(ARGS["--root"])
    C = common.Common(ROOT)

    if ARGS["<command>"] != "config":
        if not C.config_file.is_file():  # config file not in "." directory
            logger.warning(f"{C.config_file.name} not found in '{ROOT}', trying one level up.")
            C = common.Common(ROOT / "..")  # try in the parent directory
            if not C.config_file.is_file():  # not found in '..', stop.
                logger.error(f"{C.config_file.name} not found in '{ROOT / '..'}'. " +
                             f"Correct root_path value?")
                sys.exit()
            logger.warning(f"Loading {C.config_file.name} found in " +
                           f"'{C.config_file.parent}'")

    # Launch tree

    if ARGS["<command>"] == "config":
        if "help" in ARGS["<args>"]:
            exit(config.__doc__)
        subargs = docopt(config.__doc__)
        config(subargs)

    elif ARGS["<command>"] == "sample":
        if "help" in ARGS["<args>"]:
            exit(sampling.__doc__)
        subargs = docopt(sampling.__doc__)
        sampling.run(C, subargs)

    elif ARGS["<command>"] == "generate":
        if "help" in ARGS["<args>"]:
            exit(generate.__doc__)
        subargs = docopt(generate.__doc__)
        generate(C, subargs)

    elif ARGS["<command>"] == "resources":
        if "help" in ARGS["<args>"]:
            # workaround: avoiding importing module until use, banner Kratos
            # print(reconstruction.__doc__)
            # print(reconstruction.reconstruct_displacement.__doc__)
            # print(reconstruction.reconstruct_damage.__doc__)
            # Printting our own help for now...
            exit("Reconstruction help: add docs here")
        resources()

    elif ARGS["<command>"] == "validate":
        if "help" in ARGS["<args>"]:
            exit(multiscale.__doc__)
        multiscale.run(C)

    elif ARGS["<command>"] in ["help", None]:
        exit(__doc__)

    else:
        exit(
            "{} is not a hprfe2 command. See 'hprfe2 --help'.".format(ARGS["<command>"])
        )

    # logger.info("--- FINISH ---")
